export const HEADER_IMG_URL = "https://lh3.googleusercontent.com/Em7AHf7XBH_RtGfCBVXz9RH8SM_pHkj3xPP-yd3cRguY1_Jc8fmqgx6WxnvGVyPV5xs5gL3HCD0FCuv6Xo4CwoY6ak4=w100-rw";
export const CARD_IMG = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/hpncnz3sfv3gigsukkts";
export const IMG_CDN_URL ="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
export const FETCH_MENU_URL = "https://www.swiggy.com/dapi/menu/v4/full?lat=12.9351929&lng=77.62448069999999&menuId=";
export const restaurantList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "437310",
        name: "Soul Rasa",
        uuid: "31d39a67-f8cc-41f2-b1f8-fafa2c85e188",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "o11yrq1ftikvipvnwwsa",
        cuisines: [
          "Indian",
          "Healthy Food",
          "Home Food",
          "South Indian",
          "North Indian",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "hb-whitefield-whitefield-2",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "# 152A Santosh Tower 4th floor EPIP Industrial Area Phase-1 Whitefield Near BMTC Bus Depot Bangalore-560066",
        locality: "1st Phase ",
        parentId: 239281,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "Flat ₹100 off",
          shortDescriptionList: [
            {
              meta: "Flat ₹100 off on orders above ₹249",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹100 off on orders above ₹249 | Use code FLAT100",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹100 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLAT100",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹100 off on orders above ₹249 | Use code FLAT100",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "promoted",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5744686~p=1~eid=00000185-e29b-654a-03b6-f4b50083016b",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "437310",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "479322",
        name: "AL PAKIZA RESTAURANT",
        uuid: "503ec584-a747-418d-a1b4-2e4b83235d73",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "qjljwjeq6mfjw8yafalg",
        cuisines: ["Indian", "Beverages"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 4.599999904632568,
        slugs: {
          restaurant: "al-pakiza-restaurant-marathahalli-marathahalli",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "NO 55/1 SHIRIDI SAI LAYOUT NEAR SAI  BABA TEMPLE ROAD MUNEKOLALU  MARATHALLI , Mahadevapura , B.B.M.P  East, Karnataka-560037",
        locality: "Munekollal",
        parentId: 283679,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "479322",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 4.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "296209",
        name: "Anjarai Petti",
        uuid: "976f0234-8bcc-4808-9b0e-3cc1fa60c1af",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "bvsm2qdhsmma2zjfudka",
        cuisines: ["South Indian", "Chinese"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "anjarai-petti-marathahalli-marathahalli",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Shan's Kitchen,SHOP NO.1 SITE, 4, 60 FEET RD, GATE, LAKSHMINARAYANA PURA, AECS LAYOUT, MARATHAHALLI - BENGALURU, Mahadevapura , B.B.M.P East, Karnataka-560037",
        locality: "AECS Layout",
        parentId: 33621,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT150 off",
          shortDescriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹150 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "296209",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "C",
        id: "94365",
        name: "Kitchens of Punjab",
        uuid: "8918e4ac-61e2-4c79-a706-b2632c48163d",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "gdkcctcz3wxe8cohsiy2",
        cuisines: ["Punjabi", "North Indian", "Thalis", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.700000047683716,
        slugs: {
          restaurant: "kitchens-of-punjab-whitefield",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "GILLY'S RESTO BAR, # 43, 1ST FLOOR, BHAGINI ICON BUSINESS HOTEL, KUNDANAHALLI GATE, ABOVE BHIMA JEWELRY, BANGALORE - 560037",
        locality: "Kundalahalli",
        parentId: 6663,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "30% off",
          shortDescriptionList: [
            {
              meta: "30% off | Use JUMBO",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "30% off up to ₹150 on orders above ₹479 | Use code JUMBO",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "30% OFF",
          shortDescriptionList: [
            {
              meta: "Use JUMBO",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "30% off up to ₹150 on orders above ₹479 | Use code JUMBO",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "promoted",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5601099~p=4~eid=00000185-e29b-654a-03b6-f4b600830455",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "94365",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 3.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "67547",
        name: "Vijayawada Heights",
        uuid: "85caa167-05d7-4a5d-a313-47a10465570e",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "x9pplqkscynzeyuqyqeh",
        cuisines: [
          "Chinese",
          "South Indian",
          "North Indian",
          "Desserts",
          "Fast Food",
          "Kerala",
          "Andhra",
          "Beverages",
          "Seafood",
          "Punjabi",
          "Hyderabadi",
        ],
        tags: [],
        costForTwo: 55000,
        costForTwoString: "₹550 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "vijayawada-heights-whitefield-whitefield",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "1-339, 10th cross ambedkar nagar,Whitefield, Bangalore 66, OPP ROYAL MART",
        locality: "Ambedkar Nagar",
        parentId: 223336,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "67547",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "9553",
        name: "Five Star Chicken",
        uuid: "8839d984-7a74-4c2e-a2ea-4ad64596e4dd",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "tmdfu8kgn7ipa8cgk9au",
        cuisines: ["Snacks"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "five-star-chicken-white-field-whitefield",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Ground Floor, No 03, Poornima Complex, Whitfield road, Bangalore, Bengaluru (Bangalore) Urban, Karnataka, 560066",
        locality: "Poornima Complex",
        parentId: 376,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "9553",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "62980",
        name: "LunchBox - Meals and Thalis",
        uuid: "1d4f1923-f284-4daf-a5f2-8e7cfaa4a846",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "qpl5pwso5ateataxdfyk",
        cuisines: [
          "North Indian",
          "Punjabi",
          "Biryani",
          "Healthy Food",
          "Jain",
          "Thalis",
          "Indian",
          "Mughlai",
          "Desserts",
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 4.400000095367432,
        slugs: {
          restaurant: "lunchbox-kamala-complexaecs-layout-marathahalli",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "NO. 123, Kamala Complex,AECS Layout, ITPL main road,Bangalore 560037,Land Mark  Above Madhu Loka",
        locality: "AECS Layout",
        parentId: 4925,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "promoted",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4600,
          message: "",
          title: "Delivery Charge",
          amount: "4600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5780436~p=7~eid=00000185-e29b-654a-03b6-f4b700830724",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "62980",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 4.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "376442",
        name: "LAKEVIEW MILK BAR",
        uuid: "1d4966b0-6d42-4117-a946-345211184f16",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "qyqkbiryjgqn7w9gujfx",
        cuisines: ["Bakery", "Desserts", "Ice Cream"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 2.200000047683716,
        slugs: {
          restaurant: "lakeview-milk-bar-whitefield-whitefield",
          city: "bangalore",
        },
        cityState: "1",
        address: "273, WHITEFIELD MAIN ROAD, WHITEFIELD BANGALROE 560066",
        locality: "Whitefield",
        parentId: 585,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT125 off",
          shortDescriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹125 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "376442",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 2.200000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "377396",
        name: "Chinese Wok",
        uuid: "c9d07663-32c4-4b31-8330-8ce7abd0d538",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "k9ljnxbpf3lk39up5azt",
        cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: "chinese-wok-(wok-express)-whitefield-whitefield",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No 710 Varthur Main Road Thubarahalli Whitefield Bangalore BBMP East",
        locality: "Varthur Main Road",
        parentId: 61955,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use MISSEDYOU",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code MISSEDYOU",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use MISSEDYOU",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code MISSEDYOU",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "377396",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "339908",
        name: "Subbayya Gari Hotel",
        uuid: "744771dc-da71-4d3e-8a0a-5ac9ee74c2de",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "gmxqr3dioiugsfikrlyf",
        cuisines: ["South Indian", "Andhra", "Sweets"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 4.099999904632568,
        slugs: {
          restaurant: "subbayya-gari-hotel-marathahalli-marathahalli",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Near SHell petrol bunkStop, 4th Main Road, 'E' Block,AECS Layout,Brook Field,Marathahalli, Bangalore-560037",
        locality: "AECS Layout",
        parentId: 12343,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "promoted",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5771508~p=10~eid=00000185-e29b-654a-03b6-f4b800830a7c",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "339908",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 4.099999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "387927",
        name: "Kouzina Kafe - The Food Court",
        uuid: "9481fe92-bbeb-4b33-b8a2-15271d61c72d",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "joh3ozef5wr7u4n1rgku",
        cuisines: ["Bakery", "Desserts", "Ice Cream", "Beverages"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 3.799999952316284,
        slugs: {
          restaurant: "kouzina-kafe-–-the-food-court-whitefield-whitefield",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Shop.no - 12 & 13, 2nd Floor, Arya Hub Mall, Hope Farm Signal , Prashanth Extension , Whitefield Main Road. Bengaluru - 560066",
        locality: "Arya Hub Mall",
        parentId: 249027,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT125 off",
          shortDescriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹125 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "387927",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 3.799999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "41546",
        name: "Dhaba Estd 1986 Delhi",
        uuid: "dffc95ec-02ca-4f0e-ae8c-842e1f948a03",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "b87e0a6371cbbbb104ea9b17ebc29177",
        cuisines: [
          "Biryani",
          "Hyderabadi",
          "North Indian",
          "Indian",
          "Tandoor",
          "Punjabi",
        ],
        tags: [],
        costForTwo: 90000,
        costForTwoString: "₹900 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 6.800000190734863,
        slugs: {
          restaurant: "dhaba-estd-1986-delhi-outer-ring-road-marathahalli",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "first floor, ntr royal plaza,above athome,89/1 monnekolala village, varthur hobli,outer ring road, marathahalli,banglore, 560037",
        locality: "Monnekolala",
        parentId: 11239,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "60% off",
          shortDescriptionList: [
            {
              meta: "60% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "60% off up to ₹120 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "60% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "60% off up to ₹120 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "promoted",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5663728~p=13~eid=00000185-e29b-654a-03b6-f4b900830d70",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "41546",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 6.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "593472",
        name: "Grill Factory",
        uuid: "3c001508-e5d4-4949-9213-2e87767b3da3",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "yabdhpx21zk24cnczpnf",
        cuisines: ["Arabian", "Lebanese"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 4,
        slugs: {
          restaurant: "grill-factory-whitefield-whitefield",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "#166, Mann Food Court, A K Gopalan Colony Main Rd, Ambedkar Nagar, Whitefield, Bengaluru, Karnataka 560066, India",
        locality: "Ambedkar Nagar",
        parentId: 7289,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "30% off",
          shortDescriptionList: [
            {
              meta: "30% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "30% off up to ₹75 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "30% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "30% off up to ₹75 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "593472",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 4,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "319411",
        name: "Combo King's",
        uuid: "defeddb7-df77-4d01-9930-50d4354c61a9",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "bsudej2alf7gew0uvloo",
        cuisines: ["Combo", "Biryani", "Desserts"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 4.599999904632568,
        slugs: {
          restaurant: "combo-kings-kadubeesanahalli-kadubeesanahalli",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "7DAYS KITCHEN, Manjunatha Layout, Thubarahalli, Marathahalli, Bengaluru, Karnataka, India",
        locality: "Manjunatha Layout",
        parentId: 305853,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "319411",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 4.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "198493",
        name: "Leon's - Burgers & Wings (Leon Grill)",
        uuid: "770f712b-79a2-4ac8-8eba-342952688f18",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "f6okwzxzdjj94xwuyy9l",
        cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 3.5,
        slugs: {
          restaurant: "leon-grillaa-5th-block-koramangala",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Prasanth Layout, Prasanth Extension, Whitefield, Bengaluru, Karnataka 560066",
        locality: "Prasanth Layout",
        parentId: 371281,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹100 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹100 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "restaurant",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "promoted",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5777286~p=16~eid=00000185-e29b-654a-03b6-f4ba00831020",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "198493",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 3.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
  ];